# Generated by Django 5.2.10 on 2026-01-23 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('isbn_13', models.CharField(max_length=13, unique=True)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('author_royalty_rate', models.DecimalField(decimal_places=2, help_text='Percentage, e.g. 0.15 for 15%', max_digits=5)),
                ('total_sales_to_date', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(related_name='books', to='bookapp.author')),
                ('publisher_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('publisher_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author_paid', models.BooleanField(default=False)),
                ('author_royalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='bookapp.book')),
            ],
        ),
    ]
