# Generated by Django 5.2.10 on 2026-01-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_royalty_rate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='author_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='author_royalty_amount',
        ),
        migrations.CreateModel(
            name='AuthorSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author_paid', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='bookapp.author')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_sales', to='bookapp.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='authors',
            field=models.ManyToManyField(related_name='sales', through='bookapp.AuthorSale', to='bookapp.author'),
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royalty_rate', models.DecimalField(decimal_places=4, help_text='Royalty rate as a decimal (e.g. 0.15 for 15%)', max_digits=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
            ],
            options={
                'unique_together': {('author', 'book')},
            },
        ),
    ]
