# Generated by Django 5.2.10 on 2026-01-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_book_author_royalty_rate_remove_book_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='bookapp.AuthorBook', to='bookapp.author'),
        ),
    ]
