# Generated by Django 5.2.11 on 2026-02-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher_user',
        ),
    ]
