# Generated by Django 5.2.11 on 2026-02-07 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_sales_to_date',
        ),
        migrations.AlterField(
            model_name='authorbook',
            name='royalty_rate',
            field=models.DecimalField(decimal_places=4, help_text='Royalty rate as a decimal (e.g. 0.15 for 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='ISBN-10 must be 10 characters: 9 digits followed by a digit or X.', regex='^\\d{9}[\\dXx]$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN-13 must be exactly 13 digits.', regex='^\\d{13}$')]),
        ),
    ]
