# Generated by Django 5.2.11 on 2026-02-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_remove_book_total_sales_to_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='example@example.com', help_text="Author's primary contact email", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
