# Generated by Django 5.2.11 on 2026-02-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_remove_author_bio_author_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='authors',
        ),
        migrations.AddField(
            model_name='sale',
            name='author_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='author_royalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_source',
            field=models.CharField(choices=[('distributor', 'Distributor'), ('handsold', 'Handsold')], default='distributor', max_length=20),
        ),
        migrations.DeleteModel(
            name='AuthorSale',
        ),
    ]
