# Generated by Django 5.2.11 on 2026-02-25 20:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_remove_author_bio_author_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorbook',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='authorbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='bookapp.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_path',
            field=models.CharField(blank=True, help_text='Optional path to a web-viewable cover image (e.g. /static/covers/mybook.jpg).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Non-negative cover price.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='distributor_author_royalty_rate',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Percentage of publisher revenue paid to the author for distributor sales (decimal, e.g. 0.50).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='book',
            name='hand_sold_author_royalty_rate',
            field=models.DecimalField(decimal_places=4, default=0.2, help_text='Percentage of publisher revenue paid to the author for hand-sold books (decimal, e.g. 0.20).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='book',
            name='print_cost',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Non-negative print cost.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='series_name',
            field=models.CharField(blank=True, help_text='Optional series name. Display as "Series (position)".', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series_position',
            field=models.PositiveIntegerField(blank=True, help_text='Optional positive position within the series; required if series_name is set.', null=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('series_name__isnull', True), ('series_position__isnull', True)), models.Q(('series_name__isnull', False), ('series_position__isnull', False)), _connector='OR'), name='book_series_name_and_position_together'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('series_name__isnull', False), ('series_position__isnull', False)), fields=('series_name', 'series_position'), name='unique_series_position'),
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
    ]
