# Generated by Django 5.2.11 on 2026-02-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_alter_authorbook_unique_together_and_more'),
        ('bookapp', '0010_remove_sale_authors_sale_author_paid_and_more'),
    ]

    operations = [
    ]
