# Generated by Django 5.2.11 on 2026-02-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_merge_20260227_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, help_text="Author's primary contact email", max_length=254, null=True, unique=True),
        ),
    ]
