# Generated by Django 5.2.11 on 2026-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_alter_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, help_text="Author's primary contact email", max_length=254, null=True),
        ),
    ]
