# Generated by Django 5.2.12 on 2026-03-18 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_alter_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amazon_asin_ebook',
            field=models.CharField(blank=True, help_text="Amazon's unique identifier for the ebook edition of this book (e.g. B09XYZ1234). Optional.", max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Amazon ASIN must be exactly 10 uppercase alphanumeric characters (e.g. B09XYZ1234).', regex='^[A-Z0-9]{10}$')]),
        ),
    ]
