# Generated by Django 5.2.12 on 2026-03-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_book_amazon_asin_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='distributor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='format',
            field=models.CharField(choices=[('print', 'Print'), ('ebook', 'Ebook'), ('kindle unlimited', 'Kindle Unlimited')], default='print', max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='kenp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='publisher_revenue_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
