# Generated by Django 5.2.12 on 2026-03-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0015_sale_currency_sale_distributor_sale_format_sale_kenp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='author_royalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Computed author royalty in USD. Cannot be overridden.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='distributor',
            field=models.CharField(blank=True, choices=[('Ingram Spark', 'Ingram Spark'), ('Amazon', 'Amazon'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='publisher_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Publisher revenue normalized to USD. Used for royalty computations.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
