# Generated by Django 5.2.12 on 2026-04-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_alter_sale_author_royalty_alter_sale_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='paypal',
            field=models.CharField(blank=True, help_text="Author's account name for PayPal (paypal.me username, not email)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='venmo',
            field=models.CharField(blank=True, help_text="Author's account name for Venmo", max_length=100, null=True),
        ),
    ]
