# Generated by Django 5.2.13 on 2026-04-10 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_alter_sale_author_royalty_alter_sale_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kickstarter_item_tag_ebook',
            field=models.CharField(blank=True, help_text='Kickstarter tag for the ebook edition (e.g. "ebook-the-hobbit"). Optional.', max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Kickstarter item tag must contain no whitespace.', regex='^\\S+$')]),
        ),
        migrations.AddField(
            model_name='book',
            name='kickstarter_item_tag_print',
            field=models.CharField(blank=True, help_text='Kickstarter tag for the print edition (e.g. "paperback-the-hobbit"). Optional.', max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='Kickstarter item tag must contain no whitespace.', regex='^\\S+$')]),
        ),
        migrations.AddField(
            model_name='book',
            name='released',
            field=models.BooleanField(default=False, help_text='Indicates whether this book has been released to the public. Only released books are eligible for author royalty payment.'),
        ),
    ]
