# Generated by Django - Add kickstarter sale source

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0018_merge_20260412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_source',
            field=models.CharField(
                choices=[
                    ('distributor', 'Distributor'),
                    ('handsold', 'Handsold'),
                    ('kickstarter', 'Kickstarter'),
                ],
                default='distributor',
                max_length=20,
            ),
        ),
    ]
